version: "3.8"
# networks:
#   mqtt-net:
#     # driver: bridge
#     # ipam:
#     #   driver: default
#     #   config:
#     #     - subnet: 172.100.10.0/24

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  fault_handler:
    # image: fault_handler
    build:
      context: ./FaultHandler
      dockerfile: Dockerfile
    depends_on:
      - mosquitto

  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_DATABASE: "sensorData"
  #     MYSQL_USER: "user"
  #     MYSQL_PASSWORD: "password"
  #     MYSQL_ROOT_PASSWORD: "password"
  #   ports:
  #     - "3306:3306"
  #   healthcheck:
  #       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #       timeout: 2s
  #       retries: 10

  # publisher:
  #   image: publisher:test
  #   build:
  #     context: ./publisher
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mosquitto
  #     - db

  # subscriber:
  #   image: subscriber:test
  #   build:
  #     context: ./subscriber
  #     dockerfile: Dockerfile
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #       restart: true